version: '2'
services:
  web: 
    container_name: web
    build: ./docker
    ports: 
      - "3000:80"
    volumes:
      - .:/var/www
    links:
      - "db"

  db: 
        container_name: db
        image: mysql:5.7
        ports:
            - "33069:3306"
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: twentyea_om 
          MYSQL_USER: test
          MYSQL_PASSWORD: test    
